import type { AppLink, Resource, Contact, Company } from '../src/data/types';

const capgrupoLogo = 'https://www.google.com/s2/favicons?domain=capgrupo.com&sz=64';
const fastbiLogo = '/logos/fastbi.png';

export const apps: AppLink[] = [
  {
    id: 'erp-cap',
    name: 'ERP CAP',
    description: 'Sistema ERP de Grupo CAP.',
    url: 'https://cap.capgrupo.com/login',
    category: 'erp',
    featured: true,
    company: 'Grupo CAP',
    logo: fastbiLogo,
  },
  {
    id: 'erp-sym',
    name: 'ERP S&M',
    description: 'Sistema ERP de Inversiones S&M.',
    url: 'https://sym.capgrupo.com/login',
    category: 'erp',
    featured: false,
    company: 'Inversiones S&M',
    logo: fastbiLogo,
  },
  {
    id: 'erp-japan',
    name: 'ERP Japan',
    description: 'Sistema ERP de Japan HN.',
    url: 'https://japan.capgrupo.com/login',
    category: 'erp',
    featured: false,
    company: 'Japan HN',
    logo: fastbiLogo,
  },
  {
    id: 'erp-mansiago',
    name: 'ERP Mansiago',
    description: 'Sistema ERP de Distribuidora Mansiago.',
    url: 'https://mansiago.capgrupo.com/login',
    category: 'erp',
    featured: false,
    company: 'Distribuidora Mansiago',
    logo: fastbiLogo,
  },
  {
    id: 'erp-blessing',
    name: 'ERP Blessing',
    description: 'Sistema ERP de Auto Repuestos Blessing.',
    url: 'https://blessing.capgrupo.com/login',
    category: 'erp',
    featured: false,
    company: 'Auto Repuestos Blessing',
    logo: fastbiLogo,
  },
  {
    id: 'erp-didasa',
    name: 'ERP Didasa',
    description: 'Sistema ERP de Tecnicentro DIDASA.',
    url: 'https://didasa.capgrupo.com/login',
    category: 'erp',
    featured: false,
    company: 'Tecnicentro DIDASA',
    logo: fastbiLogo,
  },
  {
    id: 'outlook',
    name: 'Outlook',
    description: 'Correo corporativo del grupo.',
    url: 'https://outlook.office.com',
    category: 'microsoft365',
    featured: true,
    logo: 'https://www.google.com/s2/favicons?domain=outlook.office.com&sz=64',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    description: 'Chat, reuniones y llamadas internas.',
    url: 'https://teams.microsoft.com',
    category: 'microsoft365',
    featured: true,
    logo: 'https://www.google.com/s2/favicons?domain=teams.microsoft.com&sz=64',
  },
  {
    id: 'sharepoint',
    name: 'SharePoint',
    description: 'Documentos y sitios compartidos por empresa.',
    url: 'https://cap365.sharepoint.com',
    category: 'microsoft365',
    featured: false,
    logo: 'https://www.google.com/s2/favicons?domain=sharepoint.com&sz=64',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    description: 'Archivos personales en la nube.',
    url: 'https://onedrive.live.com',
    category: 'microsoft365',
    featured: false,
    logo: 'https://www.google.com/s2/favicons?domain=onedrive.live.com&sz=64',
  },
  {
    id: 'portal-colaborador',
    name: 'Portal del Colaborador',
    description: 'Acceso al portal del colaborador.',
    url: 'https://cap.capgrupo.com/public/employee',
    category: 'portals',
    featured: true,
    logo: capgrupoLogo,
  },
  {
    id: 'tworks',
    name: 'T-Works',
    description: 'Gestión de proyectos y tareas.',
    url: 'https://pavemi.com/projects/158',
    category: 'tools',
    featured: true,
    logo: 'https://www.google.com/s2/favicons?domain=pavemi.com&sz=64',
  },
  {
    id: 'solicitudes-ti',
    name: 'Solicitudes Interdepartamentales',
    description: 'Solicitudes de soporte con SLA y métricas.',
    url: 'https://fastbi-ti-76ufimak.manus.space',
    category: 'tools',
    featured: false,
    badge: 'nuevo',
    logo: 'https://www.google.com/s2/favicons?domain=manus.space&sz=64',
  },
  {
    id: 'tickets-ti',
    name: 'Tickets TI',
    description: 'Seguimiento de tickets y métricas de TI.',
    url: 'https://captickets-5qnbftqy.manus.space',
    category: 'tools',
    featured: true,
    badge: 'nuevo',
    logo: 'https://www.google.com/s2/favicons?domain=manus.space&sz=64',
  },
  {
    id: 'soporte-tecnico',
    name: 'Soporte Técnico',
    description: 'Gestión de mantenimiento y equipos técnicos.',
    url: 'https://flotamanage-7utvauea.manus.space/mantenimiento',
    category: 'tools',
    featured: false,
    badge: 'nuevo',
    logo: 'https://www.google.com/s2/favicons?domain=manus.space&sz=64',
  },
  {
    id: 'soporte-m365',
    name: 'Soporte M365 en Teams',
    description: 'Canal de soporte de Microsoft 365 y productividad.',
    url: 'https://teams.microsoft.com/l/channel/19:eab7e3bfaa5043dd9f4efc43d5675690@thread.tacv2/Soporte%20M365%20Y%20Herramientas%20de%20Productividad?groupId=57d5e5fa-98ce-463a-acef-fef73f9a9d02&tenantId=14aaec29-211a-475d-8301-3046ff004c6',
    category: 'tools',
    featured: false,
    logo: 'https://www.google.com/s2/favicons?domain=teams.microsoft.com&sz=64',
  },
  {
    id: 'fastbi-projects',
    name: 'FastBI Projects',
    description: 'Gestión de proyectos internos.',
    url: 'https://project.capgrupo.com/',
    category: 'tools',
    featured: false,
  },
  {
    id: 'cap-recruit',
    name: 'CAP Recruit',
    description: 'Reclutamiento y selección de personal.',
    url: 'https://recruit.capgrupo.com',
    category: 'talent',
    featured: false,
    logo: '/logos/recruit.png',
  },
  {
    id: 'talentia',
    name: 'Talentia',
    description: 'Evaluaciones y gestión de talento.',
    url: 'https://talentia.moniteck.com/',
    category: 'talent',
    featured: false,
  },
  {
    id: 'marketing-cap',
    name: 'Marketing CAP',
    description: 'Gestión de marketing del grupo.',
    url: 'https://marke.capgrupo.com/',
    category: 'marketing',
    featured: false,
  },
  {
    id: 'fastbi-reviews',
    name: 'FastBI Reviews',
    description: 'Gestión de reseñas de clientes.',
    url: 'https://reviews.capgrupo.com/dashboard',
    category: 'marketing',
    featured: false,
    company: 'Tecnicentro DIDASA',
  },
  {
    id: 'tally',
    name: 'Tally',
    description: 'Formularios y encuestas del grupo.',
    url: 'https://tally.capgrupo.com/',
    category: 'marketing',
    featured: false,
    logo: '/logos/tally.png',
  },
];

export const resources: Resource[] = [
  {
    id: 'manual-erp',
    name: 'Manual del ERP',
    description: 'Guía de uso del sistema de facturación.',
    url: 'https://cap365.sharepoint.com/manuales/erp',
    type: 'manual',
  },
  {
    id: 'manual-induccion',
    name: 'Manual de Inducción',
    description: 'Bienvenida y políticas para personal nuevo.',
    url: 'https://cap365.sharepoint.com/manuales/induccion',
    type: 'manual',
  },
  {
    id: 'plantilla-memo',
    name: 'Plantilla de Memorándum',
    description: 'Formato oficial para comunicados internos.',
    url: 'https://cap365.sharepoint.com/plantillas/memo',
    type: 'template',
  },
  {
    id: 'plantilla-presentacion',
    name: 'Plantilla de Presentación',
    description: 'PowerPoint con la identidad del grupo.',
    url: 'https://cap365.sharepoint.com/plantillas/ppt',
    type: 'template',
  },
  {
    id: 'carpeta-gerencia',
    name: 'Carpeta de Gerencia',
    description: 'Documentos compartidos de gerencia general.',
    url: 'https://cap365.sharepoint.com/gerencia',
    type: 'folder',
  },
  {
    id: 'directorio-proveedores',
    name: 'Directorio de Proveedores',
    description: 'Listado maestro de proveedores del grupo.',
    url: 'https://cap365.sharepoint.com/proveedores',
    type: 'link',
  },
];

export const contacts: Contact[] = [
  {
    name: 'Nombre Apellido',
    role: 'Gerente General',
    department: 'Gerencia',
    company: 'Grupo CAP',
    phone: '+504 9990-0823',
    email: 'gerencia@cap.hn',
  },
  {
    name: 'Nombre Apellido',
    role: 'Gerente de Tecnología',
    department: 'Tecnología',
    company: 'Grupo CAP',
    phone: '+504 9000-0000',
    email: 'ti@cap.hn',
    extension: '101',
  },
  {
    name: 'Nombre Apellido',
    role: 'Soporte Técnico',
    department: 'Tecnología',
    company: 'Grupo CAP',
    phone: '+504 9000-0001',
    email: 'soporte@cap.hn',
    extension: '102',
  },
  {
    name: 'Nombre Apellido',
    role: 'Jefe de Recursos Humanos',
    department: 'Recursos Humanos',
    company: 'Grupo CAP',
    phone: '+504 9000-0002',
    email: 'rrhh@cap.hn',
  },
  {
    name: 'Nombre Apellido',
    role: 'Contadora General',
    department: 'Contabilidad',
    company: 'Grupo CAP',
    phone: '+504 9000-0003',
    email: 'contabilidad@cap.hn',
    extension: '201',
  },
  {
    name: 'Nombre Apellido',
    role: 'Gerente de Ventas',
    department: 'Ventas',
    company: 'Inversiones S&M',
    phone: '+504 9000-0004',
    email: 'ventas@sym.hn',
  },
];

export const companies: Company[] = [
  {
    id: 'inversiones-sm',
    name: 'Inversiones S&M',
    segment: 'Importación y Distribución B2B',
    description:
      'Empresa líder en importación y distribución de autopartes en Honduras. Servicio personalizado con cobertura nacional, entregas rápidas y atención especializada a talleres, distribuidores y flotillas.',
    slogan: 'Ganando Tú, Ganamos Nosotros',
    color: '#C62828',
  },
  {
    id: 'mansiago',
    name: 'Distribuidora Mansiago',
    segment: 'Distribución de Lubricantes y Autopartes B2B',
    description:
      'Especializada en lubricantes, fluidos, filtros y autopartes de calidad. Se distingue por su confiabilidad, excelencia en servicio y respuesta inmediata con infraestructura eficiente.',
    slogan: 'Calidad que te impulsa',
    color: '#D4A843',
  },
  {
    id: 'blessing',
    name: 'Auto Repuestos Blessing',
    segment: 'Venta al Detalle B2C',
    description:
      'Referente nacional en la venta de autopartes al detalle, reconocido por su amplia variedad, precios accesibles y calidad. Servicio a domicilio y atención personalizada.',
    slogan: 'La calidad, no es cara',
    color: '#1E88E5',
  },
  {
    id: 'didasa',
    name: 'Tecnicentro DIDASA',
    segment: 'Instalación y Servicio Automotriz B2C',
    description:
      'Centro integral de mantenimiento, reparación e instalación de autopartes. Técnicos altamente capacitados con diagnóstico electrónico y mecánica general.',
    slogan: 'Tu vehículo en manos expertas',
    color: '#43A047',
  },
  {
    id: 'japan-hn',
    name: 'Japan HN',
    segment: 'Repuestos Japoneses B2B',
    description:
      'Especializada en repuestos japoneses de alta calidad. Marcas como KYB, 555, TRC, TZK, NPW, KOYO, MRK y FIC con garantía de calidad japonesa.',
    slogan: 'Calidad japonesa garantizada en cada pieza',
    color: '#E53935',
  },
  {
    id: 'cap-logistics',
    name: 'CAP Logistics',
    segment: 'Logística Especializada',
    description:
      'Gestiona la cadena de suministro del grupo, asegurando entregas oportunas y eficientes a nivel nacional e internacional con flota propia.',
    slogan: 'Eficiencia en cada entrega',
    color: '#7B1FA2',
  },
];
